'use strict';
const db=window.ROBOTICS_DAILY||{records:[],editions:[]};
const categories=[['all','全部研究','◈'],['vla','VLA · 视觉语言动作','⌘'],['wam','WAM · 世界动作模型','◎'],['rl','RL · 强化学习','↗'],['theory','经典机器人理论','∑'],['embodied','操作、导航与具身','⊞'],['systems','数据、评测与系统','▤']];
const el=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeUrl=u=>{try{const v=new URL(u);return ['https:','http:'].includes(v.protocol)?v.href:'#';}catch{return '#';}};
const fmt=t=>t?new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(t)):'尚未更新';
const sorted=[...db.editions].sort((a,b)=>b.startedAt.localeCompare(a.startedAt));
let category='all', selected=sorted[0]?.id||'all',query='';
const titleOf=c=>categories.find(x=>x[0]===c)?.[1]||c;
function currentEdition(){return sorted.find(e=>e.id===selected);}
function editionRecords(){const e=currentEdition();return e?.recordsSnapshot?e.recordsSnapshot:e?db.records.filter(r=>[...(e.addedIds||[]),...(e.updatedIds||[])].includes(r.id)):db.records;}
function renderNav(){const records=editionRecords();el('categories').innerHTML=categories.map(([id,label,symbol])=>`<button class="nav-item ${category===id?'active':''}" data-category="${id}" aria-pressed="${category===id}"><span class="symbol" aria-hidden="true">${symbol}</span><span>${label}</span><span class="count">${records.filter(r=>id==='all'||r.category===id||(r.tags||[]).includes(id)).length}</span></button>`).join('');el('categories').querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{category=b.dataset.category;render();}));}
function card(r,i){const e=currentEdition(), updated=e?.updatedIds?.includes(r.id);const fields=[['背景','background'],['创新点','innovation'],['实验与证据','experiments'],['结论','conclusion'],['评价 · 编辑分析','evaluation'],['发展方向 · 研究设想','futureDirections']];return `<article class="paper ${r.featured?'featured':''}" id="paper-${esc(r.id)}"><div class="paper-top"><div class="paper-meta"><span class="tag">${esc(titleOf(r.category).split(' · ')[0])}</span>${r.featured?'<span class="tag green">重点阅读</span>':''}${updated?'<span class="tag amber">实质更新</span>':''}${r.changeType==='follow_up_report'?'<span class="tag amber">既有研究跟进</span>':''}<span>${esc(r.type||'研究论文')}</span><span>·</span><span>${r.id.startsWith('arxiv:')?'提交':'报道'} ${esc(r.publishedAt?.slice(0,10)||'日期未核实')}</span><span>·</span><span>收录 ${esc(fmt(r.discoveredAt))}</span></div><h3>${esc(r.zhTitle||r.title)}</h3>${r.zhTitle?`<p class="en-title">${esc(r.title)}</p>`:''}<p class="paper-summary">${esc(r.summary)}</p><div class="paper-footer"><span class="evidence">${esc(r.evidence||'原始来源已核对')}</span><div class="links">${(r.links||[]).map(l=>`<a href="${esc(safeUrl(l.url))}" target="_blank" rel="noopener noreferrer">${esc(l.label)} ↗</a>`).join('')}</div></div></div>${updated&&r.changeNote?`<div class="change-note">本次变化：${esc(r.changeNote)}</div>`:''}<details ${i===0?'open':''}><summary>阅读全文分析 <span class="evidence">背景 / 创新 / 实验 / 结论 / 评价 / 展望</span></summary><div class="analysis-grid">${fields.map(([label,key],j)=>`<section class="analysis-section ${j>=4?'editorial':''}"><h4><span>0${j+1}</span>${label}</h4><p>${esc(r[key]||'当前原文未提供充分信息，待补充核实。').replace(/\n/g,'<br>')}</p></section>`).join('')}</div><div class="evidence-notes"><h4>原文定位</h4>${(r.evidenceDetails||[]).map(x=>`<p><a href="${esc(safeUrl(x.url))}" target="_blank" rel="noopener noreferrer">${esc(x.location)} ↗</a> · ${esc(x.supports)}</p>`).join('')}</div></details></article>`;}
function render(){renderNav();const e=currentEdition();const records=editionRecords().filter(r=>(category==='all'||r.category===category||(r.tags||[]).includes(category))&&(!query||JSON.stringify(r).toLowerCase().includes(query.toLowerCase()))).sort((a,b)=>Number(!!b.featured)-Number(!!a.featured)||b.publishedAt.localeCompare(a.publishedAt));el('result-title').textContent=titleOf(category);el('result-count').textContent=`${records.length} 篇研究`;el('reports').innerHTML=records.length?records.map(card).join(''):`<div class="empty"><h3>${query?'没有找到匹配的研究':'本期该方向暂无新增'}</h3><p>${query?'换一个关键词，或选择全部归档。':'切换其他研究方向，或查看历史归档。'}</p></div>`;const latest=sorted[0];el('last-update').textContent=latest?`最近检索 ${fmt(latest.completedAt||latest.startedAt)}`:'等待首期检索';el('overview').innerHTML=`<div class="stat"><strong>${e?.addedIds?.length??db.records.length}</strong><span><b>${e?'本期新收录':'累计收录'}</b>${e?.label||'全部期次'}</span></div><div class="stat"><strong>${e?.updatedIds?.length||0}</strong><span><b>研究更新</b>版本与实质进展</span></div><div class="stat"><strong>${db.records.length}</strong><span><b>累计研究</b>${db.editions.length} 次归档 · 持续去重</span></div>`;el('edition-note').innerHTML=e?`<strong>${esc(e.label)}</strong>　${esc(e.summary||'本期未发现符合收录标准的新研究。')}`:'显示所有已归档的研究；每项保留首次收录时间和最新核实内容。';const checks=(e||latest)?.sourceChecks||[];el('source-checks').innerHTML=checks.length?checks.map(s=>`<div class="source-row"><b>${esc(s.name)}</b><span>${esc(s.status)}</span><span>${esc(s.note)}</span></div>`).join(''):'首次检索完成后展示来源覆盖。';}
el('edition').innerHTML=sorted.map(e=>`<option value="${esc(e.id)}">${esc(e.label)}</option>`).join('')+'<option value="all">全部历史归档</option>';el('edition').value=selected;el('edition').addEventListener('change',e=>{selected=e.target.value;render();});el('search').addEventListener('input',e=>{query=e.target.value.trim();render();});render();
